version: '3.7'
services:
  backend-service:
    build: ./PasswordGenerator
    environment:
    - SECRET_KEY=secretkey
  numbers-service:
    build: ./RandNumsGen
    environment:
    - SECRET_KEY=secretkey
  letters-service:
    build: ./RandLetGen
    environment:
    - SECRET_KEY=secretkey
  specialchar-service:
    build: ./SpecialCharGen
    environment:
    - SECRET_KEY=secretkey
  frontend-service:
    build: ./FrontEnd
    environment:
    - SECRET_KEY=secretkey
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp

