version: '3.7'
services:
  backend:
    build: ./PasswordGenerator
    ports:
    - target: 5004
      published: 5004
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  
  numsgen:
    build: ./RandNumsGen
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  
  letgen:
    build: ./RandLetGen
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  specialchargen:
     build: ./SpecialCharGen
     ports:
     - target: 5003
       published: 5003
       protocol: tcp
     environment:
     - SECRET_KEY=secretkey
     networks:
     - my-network
    
  frontend:
    build: ./FrontEnd
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
    depends_on:
    - backend

networks:
  my-network:
