version: '3.7'
services:
  passwordgenerator:
    image: alinadenisa/passwordgenerator:latest
    container_name: passwordgenerator
    depends_on:
    - randnumsgen
    - randletgen
    - specialchargen

  randnumsgen:
    image: alinadenisa/randnumsgen:${version}
    container_name: randnumsgen
    
  randletgen:
    image: alinadenisa/randletgen:${version}
    container_name: randletgen
 
  specialchargen:
    image: alinadenisa/specialchargen:${version}
    container_name: specialchargen
   
  frontend-service:
    image: alinadenisa/frontend:latest
    container_name: frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
    - DATABASE_URI=mysql+pymysql://root:password@http://db:3306/db
    - SECRET_KEY=mysecretkey
    depends_on:
    - passwordgenerator

  db:
    image: alinadenisa/db:latest
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - frontend-service
