apiVersion: v1
kind: Service
metadata:
  name: passwordgenerator
spec:
  selector:
    app: passwordgenerator
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passwordgenerator
  labels: 
    app: passwordgenerator
spec:
  selector:
    matchLabels:
      app: passwordgenerator
  template:
    metadata:
      labels:
        app: passwordgenerator
    spec:
      containers:
      - name: passwordgenerator
        image: alinadenisa/passwordgenerator:latest
        ports:
        - containerPort: 5000
