apiVersion: v1
kind: Service
metadata:
  name: randletgen
spec:
  selector:
    app: randletgen
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randletgen
  labels: 
    app: randletgen
spec:
  selector:
    matchLabels:
      app: randletgen
  template:
    metadata:
      labels:
        app: randletgen
    spec:
      containers:
      - name: randletgen
        image: alinadenisa/randletgen:V2
        ports:
        - containerPort: 5000
