apiVersion: v1
kind: Service
metadata:
  name: specialchargen
spec:
  selector:
    app: specialchargen
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialchargen
  labels: 
    app: specialchargen
spec:
  selector:
    matchLabels:
      app: specialchargen
  template:
    metadata:
      labels:
        app: specialchargen
    spec:
      containers:
      - name: specialchargen
        image: alinadenisa/specialchargen:V2
        ports:
        - containerPort: 5000
